### ISSUE TITLE
group-member no longer works (Server 7.19.7)

### ISSUE THREAD

**Issue by ghost** [glewe/confluence-user-macros#2]
https://github.com/glewe/confluence-user-macros/tree/master/src/group-members

The "group members" macro worked until the upgrade of confluence server 7.19.0 to 7.19.7

It looks like some API calls are deprecated : like : ".getGroup"

I am a litte lost here on how to fix this.
Can you please give me a pointer on how to fix the plugin so it works on Confluence server 7.19.7?

**Comment by glewe** [comment]
Hi @bernardflach ,
we are still on 7.13.8 so I cannot test it. The API documentation for 7.19.7 though still lists getGroup() as a valid method of the UserAccessor interface:
https://docs.atlassian.com/ConfluenceServer/javadoc/7.19.7/com/atlassian/confluence/user/UserAccessor.html
I can only address this after we have upgraded to 7.19 LTS.
Best regards,
George

**Comment by ghost** [comment]
Hi George,

Perhaps yopu know this one (using user macro's)
can i convert a string from uppercase to lowercase?

i cannot find this in the documentation of atlassoian on user macro's

Met vriendelijke groet,

Bernard Flach
________________________________
Van: George Lewe ***@***.***>
Verzonden: donderdag 13 april 2023 14:58
Aan: glewe/confluence-user-macros ***@***.***>
CC: Bernard Flach ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [glewe/confluence-user-macros] group-member no longer works (Server 7.19.7) (Issue #2)


Hi @bernardflach<https://github.com/bernardflach> ,
we are still on 7.13.8 so I cannot test it. The API documentation for 7.19.7 though still lists getGroup() as a valid method of the UserAccessor interface:
https://docs.atlassian.com/ConfluenceServer/javadoc/7.19.7/com/atlassian/confluence/user/UserAccessor.html
I can only address this after we have upgraded to 7.19 LTS.
Best regards,
George

**Comment by glewe** [comment]
Hi @bernardflach ,
we are now on 7.19.9 LTS and the Group Member macro still works fine. I can't tell why it wouldn't do so on your end.

In regards to the lowercase question, I found this post:
[https://stackoverflow.com/questions/6998412/velocity-string-function](https://stackoverflow.com/questions/6998412/velocity-string-function)
I haven't tested it but it looks logical to me.

Best regards,
George

**Comment by glewe** [comment]
Sorry, my bad. The system I checked is still on 7.13.8. I will test again in our integration environment and reopen this issue...

**Comment by glewe** [comment]
Hi @bernardflach ,
I turns out that the API calls are still available but disabled in 7.19. You need to enable them again as described here:
[https://jira.atlassian.com/browse/CONFSERVER-82741](https://jira.atlassian.com/browse/CONFSERVER-82741)
The second workaround in that issue allows you to specify what you want.
Best regards,
George
